apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'some insane and awful named doc'
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
  description: An example of a Backstage application.
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: user-or-team-name
